import './globals.css'
import { Inter } from 'next/font/google'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // const user = await getCurrentUser()

  //   if (!user) {
  //       redirect("/auth/login")
  //   }
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}